/**
 * Result returned by an adapter probe operation inspecting CLI installation and authentication state.
 */
import type { AdapterEvent, ExecutionError, TerminalStatus } from './conversation.types.js';
export * from './conversation.types.js';

export interface AdapterProbeResult {
  /** Unique adapter identifier (e.g. 'codex', 'claude', 'gemini'). */
  id?: string;
  /** Human-readable adapter display name. */
  name?: string;
  /** Whether the CLI binary was detected on the host system. */
  installed: boolean;
  /** Resolved binary path or command name. */
  command?: string;
  /** Detected CLI version string. */
  version?: string;
  /** Filesystem path to CLI executable. */
  path?: string;
  /** Adapter-specific configuration metadata. */
  config?: { defaultModel?: string; defaultReasoningEffort?: string; sandboxMode?: string };
  /** Path to local CLI configuration directory or file. */
  configPath?: string;
  /** List of model identifiers available on the host CLI. */
  availableModels?: string[];
  /** Supported reasoning effort tiers (e.g. ['low', 'medium', 'high', 'extra_high']). */
  supportedReasoningEfforts?: string[];
  /** Authentication status string (e.g. 'authenticated', 'unauthenticated', 'unknown'). */
  authStatus?: string;
  /** Authentication method in use (e.g. 'chatgpt', 'api_key', 'oauth'). */
  authMethod?: string;
  /** Logged-in username or profile identifier. */
  activeAccount?: string;
  /** Alternative account identifier alias. */
  account?: string;
  /** Guidance command for signing in if unauthenticated. */
  loginHint?: string;
  executionSupported?: boolean;
  capabilities?: { resume: boolean; streaming: boolean; readOnlyVerified: boolean; reasoningEffort: boolean };
  modelSource?: string;
  authEvidence?: string[];
  quota?: {
    measured: boolean;
    headroomPercent?: number | null;
    usedPercent?: number | null;
    resetsAt?: string | null;
    window?: string;
    buckets?: Array<{ id: string; name: string; window: string; remainingFraction: number; resetTime: string }>;
  };
}

/**
 * Output resulting from executing a prompt against a CLI adapter.
 */
export interface ExecutionResult {
  /** Whether execution failed or exited with an error. */
  isError: boolean;
  /** Complete output text generated by the agent CLI. */
  output: string;
  /** Optional error trace or failure message. */
  errorDetail?: string;
  /** Persistent conversation/thread identifier for multi-turn sessions. */
  threadId?: string | null;
  /** Process exit status code. */
  exitCode?: number | null;
  /** Legacy helpers may omit this; registered adapters require a terminal result. */
  status?: TerminalStatus;
  error?: ExecutionError;
  nativeSessionId?: string | null;
  signal?: NodeJS.Signals | null;
  model?: string;
  truncated?: boolean;
  continuationAvailable?: boolean;
  usage?: { source: 'provider'; inputTokens?: number; outputTokens?: number; totalTokens?: number };
}

export interface TerminalExecutionResult extends ExecutionResult {
  status: TerminalStatus;
  truncated: boolean;
  continuationAvailable: boolean;
}

/**
 * Options configuring adapter execution.
 */
export interface ExecutionOptions {
  /** Current working directory for CLI execution. */
  cwd?: string;
  /** Model override name. */
  model?: string;
  /** Reasoning effort level override. */
  reasoningEffort?: string;
  /** Cancellation signal for interrupting execution. */
  abortSignal?: AbortSignal;
  /** Real-time progress callback. */
  onProgress?: (info: { message?: string; percent?: number }) => void;
  /** Existing thread or session ID for resuming multi-turn conversation. */
  threadId?: string | null;
  /** Explicit user confirmation flag for top-tier reasoning engines. */
  userConfirmed?: boolean;
  timeoutMs?: number;
  nativeSessionId?: string | null;
  onEvent?: (event: AdapterEvent) => void;
}

/**
 * Progress reporting callback function signature.
 */
export interface ProgressReporter {
  (info: { message?: string; percent?: number }): void;
}

/**
 * Unified contract implemented by all CLI backend adapters.
 */
export interface CliAdapter {
  /** Unique backend identifier. */
  id: string;
  /** Human-readable backend name. */
  name: string;
  /** Probes the environment to verify CLI presence, version, and auth status. */
  probe(): Promise<AdapterProbeResult>;
  /** Executes a prompt in a read-only sandboxed CLI process. */
  execute(prompt: string, options?: ExecutionOptions): Promise<TerminalExecutionResult>;
  /**
   * Reads measured native quota without a model call, for adapters whose probe does not include it.
   * Called by quota inspection (doctor and quota-aware routing), never by `execute`.
   */
  inspectQuota?(probe?: AdapterProbeResult): Promise<AdapterProbeResult['quota']>;
}
