const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');

function prepareBranding() {
  const icon = fs.readFileSync(path.join(root, 'assets/logo64.png'));
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (icon.length < 24 || !icon.subarray(0, 8).equals(signature) ||
      icon.readUInt32BE(16) !== 64 || icon.readUInt32BE(20) !== 64) {
    throw new Error('assets/logo64.png must be a 64x64 PNG.');
  }
  if (icon.length > 16 * 1024) throw new Error('MCP icon must not exceed 16 KiB.');
  const target = path.join(root, 'src/generated/server-icon.ts');
  const source = [
    '/**',
    ' * Embedded MCP branding generated by scripts/branding.cjs from assets/logo64.png.',
    ' *',
    ' * @packageDocumentation',
    ' */',
    '',
    "import type { Icon } from '@modelcontextprotocol/sdk/types.js';",
    '',
    '/** Offline icon shared by server and tool metadata. Regenerate with npm run build. */',
    'export const SERVER_ICON = {',
    `  src: ${JSON.stringify('data:image/png;base64,' + icon.toString('base64'))},`,
    "  mimeType: 'image/png',",
    "  sizes: ['64x64'],",
    '} satisfies Icon;',
    '',
  ].join('\n');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== source) {
    fs.writeFileSync(target, source);
  }
  fs.copyFileSync(path.join(root, 'assets/logo256.png'), path.join(root, 'assets/logo.png'));
}

module.exports = { prepareBranding };
